### ISSUE TITLE
Getting started steps

### ISSUE THREAD

**Issue by botsbuzz** [carlosgj94/Guesser#1]
Hello Carlos,

first of all thank you for your effort on this project: looks amazing!

I'm newbie on the blockchain side: could you add a getting started guide in the Readme? (e.g. how to install on own server, etc.).

Thank you,

Stefano

**Comment by carlosgj94** [comment]
Hi! 🔮
Well, an installing readme is not coming any time soon, but others will be done by this/next week. 
The page is running in http://guesser.io, we are running in Rinkeby. If you don't know how to connect to this testnet, we are going to create an article in medium by the end of this week. 
Probably soon we will create a big deploy to the web page I wrote before, hang for that one. 
Also, running it by yourself is not that hard tho, but probably first you need to know how to create/run an ethereum/truffle app. Once you have that, it will be a simple $npm install && npm run dev.
If you have any doubts tho, pls, send me an email to carlosgj94@gmail.com 😃
