### ISSUE TITLE
Cromatic Issue

### ISSUE THREAD

**Issue by MuspelWolf** [carlosgj94/Guesser#2]
In Topics, letter colors do not match with background colors.

PUTO PI

**Comment by xPi2** [comment]
I'm looking forward to reading your color scheme proposal

**Comment by carlosgj94** [comment]
<img width="504" alt="screen shot 2018-04-24 at 19 10 18" src="https://user-images.githubusercontent.com/4912635/39202773-360f5e28-47f3-11e8-86c3-bc5a9b889497.png">
Done ✅
